com:
  skuniv:
    cs:
      geonyeong:
        kaggle:
          crypt:
            key: 123456789789456123456
          es:
            host: dev-geon-test001-ncl.nfra.io
            port: 9200
            type: _doc
            index:
              post: stackoverflow
              account : stackoverflow_account

